### ISSUE TITLE
Issue getting react-native-windows installed.  Can't run rnpm windows successfully

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#543]
I'm converting an existing iOS app over to React Native so I can deploy on Windows (thanks to the new UWP support!).  I'm looking to add support to an existing React Native app.

But having issues getting dev machine set up.  I've tried rolling back to the react-native-windows version, tried rolling back the react-native version to match.  I've also messed with my package.json.  Nothing seems to work so I can't get the plugin to run and generate the Windows files.

I hit peer dependency errors regardless of how I try to install.  But I'm sure I'm missing something.

Here is the error.
```
Error: Command failed: npm install --save react-native-windows@0.30.*
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-windows@0.30.*"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: react-native-windows@0.30.*
npm ERR! Valid install targets:
npm ERR! 1.0.0, 0.30.0-rc.0, 0.29.2, 0.29.1, 0.29.0, 0.29.0-rc.0, 0.28.3, 0.28.2, 0.28.1, 0.28.0, 0.28.0-rc.1, 0.28.0-rc.0, 0.27.0, 0.27.0-rc, 0.2.5-rc7, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.1.0
npm ERR!
npm ERR!
```

Here is relevant part of package.json
`"dependencies": {
    "react": "15.2.1",
    "react-native": "0.30.0-rc.0",
    "react-native-windows": "0.30.0-rc.0"
  },`

Any help you can provide would be awesome.  Thanks.

**Comment by rozele** [comment]
@kcfgl Sorry for the inconvenience.  Last week, react-native@0.30.0 was published and unfortunately we haven't got around to publishing react-native-windows@0.30.0 (this should happen sometime this week).  In the meantime, you should be able to get around this issue by running:

rnpm windows --windowsVersion 0.30.0-rc.0

**Comment by rozele** [comment]
FYI, I published 0.30.0, so `rnpm windows` (without the `--windowsVersion` flag) should work for you now.

**Comment by kcfgl** [comment]
Thanks for the fast response @rozele.  That did the trick, I should've thought about it.

But now the linking seems off.  I guess I've missed a step somewhere.  But just to be sure my original project wasn't the project, I created a fresh one.  Got everything to install.  But when I run the project it won't compile....

`Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
------ Build started: Project: WinRNTest, Configuration: Debug ARM ------
C:\WinRNTest\windows\WinRNTest\App.xaml.cs(1,7,1,18): error CS0246: The type or namespace name 'ReactNative' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(1,7,1,18): error CS0246: The type or namespace name 'ReactNative' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(2,7,2,18): error CS0246: The type or namespace name 'ReactNative' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(3,7,3,18): error CS0246: The type or namespace name 'ReactNative' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(8,22,8,31): error CS0246: The type or namespace name 'ReactPage' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(28,30,28,43): error CS0246: The type or namespace name 'IReactPackage' could not be found (are you missing a using directive or an assembly reference?)
C:\WinRNTest\windows\WinRNTest\MainPage.cs(10,32,10,49): error CS0115: 'MainPage.MainComponentName': no suitable method found to override
C:\WinRNTest\windows\WinRNTest\MainPage.cs(28,45,28,53): error CS0115: 'MainPage.Packages': no suitable method found to override
C:\WinRNTest\windows\WinRNTest\MainPage.cs(39,30,39,49): error CS0115: 'MainPage.UseDeveloperSupport': no suitable method found to override
C:\WinRNTest\windows\WinRNTest\App.xaml.cs(17,26,17,35): error CS0246: The type or namespace name 'ReactPage' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
`
If this is on my end, sorry to be a pain! But in case its related to the new build, wanted to share it.

**Comment by rozele** [comment]
I assume you're running from Visual Studio?

**Comment by rozele** [comment]
Also, make sure ReactNative is still linked in your project References:
![foo](https://cloud.githubusercontent.com/assets/1106239/17116144/69c8e358-5284-11e6-80ce-a0ea01d26f46.png)

And also double check that the react-native-windows folder exists in node_modules.  If not, then something might have gone wrong with the install.

**Comment by kcfgl** [comment]
Yep, Visual Studio on VM (Parallels). 

You're right, it isn't linked in project references, which is weird, I didn't actually change anything before trying to build.  But react-windows-native does still exist in node_modules.  I assume I can just add the reference to the ReactNative folder within react-native-windows?  Sorry if that is a dumb question, I'm an iOS guy so I'm hunting and pecking a bit in VS.

**Comment by kcfgl** [comment]
Also, ReactWindowsMap isn't referenced either.

**Comment by rozele** [comment]
ah, sorry, ReactWindowsMap is my own custom thing (you don't have to worry about it).

You're looking for these lines in your WinRNTest.csproj file:
https://github.com/ReactWindows/react-native-windows/blob/0.30-stable/local-cli/generator-windows/templates/proj/MyApp.csproj#L204-L209

**Comment by kcfgl** [comment]
Yeah those are definitely not in there. I've attempted to add the reference but its not allowing me to add ReactNative.csproj.

I'm definitely turning into a headache, sorry.

**Comment by rozele** [comment]
Not a headache at all!  Would it be possible for you to zip up your windows folder and attach it here?  I'd be happy to take a look.

**Comment by kcfgl** [comment]
Absolutely, here you go.  Thanks for taking a look.  This is just a generic starter app. Wanted to make sure a clean (but still existing) app worked before running the full existing app.

[windows.zip](https://github.com/ReactWindows/react-native-windows/files/382514/windows.zip)

Thanks again!

**Comment by rozele** [comment]
@kcfgl: from the looks of the zip folder you sent me, it looks like the ReactNative project has been removed from WinRNTest.sln.  You can add this back pretty easily by right-clicking on the Solution icon in the Solution Explorer (it says something like `Solution 'WinRNTest' (1 project)`).  Then, select "Add Existing Project" and find ../node_modules/react-native-windows/ReactWindows/ReactNative/ReactNative.csproj.

For simplicity's sake, I've posted what your final .sln file should look like on Gist:
https://gist.github.com/rozele/262b04781405d02529f8639e717b3916

You could always replace your WinRNTest file with that.

**Comment by rozele** [comment]
Also, it looks like the reference from WinRNTest.csproj to ReactNative was also lost (the one I referenced above), you can add that back by right-clicking References under the WinRNTest project, select "Add Reference" and check ReactNative from the list of solution projects (after you did the previous step).

**Comment by kcfgl** [comment]
Ugh.  My original one didn't work.  So I replaced it with yours.  Then followed your second step.  
... So ReactNative isnt listed in the list of Solution Projects.  Only WinRNTest.  I'm thinking about removing this test project and starting fresh to see what happens, instead of continuing to pepper you with questions.

**Comment by rozele** [comment]
hmm, you might have had to re-open Visual Studio to get the ReactNative project to show up in the Solution Explorer.

**Comment by kcfgl** [comment]
I went ahead and tried to build from an existing RN project. It builds on iOS and Android.  I thought we were good, the plugin installed first time and using rnpm windows appeared to work. 

BUT opening up in VS I got warnings that app.xaml, mainpage.cs, package.appmanifext and project.json were not found.  They are not in the windows/<projectname> directory.

So I built it just in case, but it failed. 
`
Y:\Arriver\node_modules\react-native-windows\ReactWindows\ReactNative\obj\ARM\Debug\DevSupport\ProgressDialog.g.cs(161,67,161,86): warning CS1591: Missing XML comment for publicly visible type or member 'ProgressDialog.GetBindingConnector(int, object)'
Y:\Arriver\node_modules\react-native-windows\ReactWindows\ReactNative\obj\ARM\Debug\DevSupport\RedBoxDialog.g.cs(369,67,369,86): warning CS1591: Missing XML comment for publicly visible type or member 'RedBoxDialog.GetBindingConnector(int, object)'
Y:\Arriver\node_modules\react-native-windows\ReactWindows\ReactNative\Touch\JavaScriptResponderHandler.cs(12,20,12,48): warning CS1574: XML comment has cref attribute 'IReactInterceptingViewParent' that could not be resolved
Y:\Arriver\node_modules\react-native-windows\ReactWindows\ReactNative\obj\ARM\Debug\XamlTypeInfo.g.cs(15,25,15,45): warning CS1591: Missing XML comment for publicly visible type or member 'XamlMetaDataProvider'
 `

**Comment by kcfgl** [comment]
Here is the output in cmd 
```

Y:\Arriver>rnpm windows
Installing react-native-windows@0.30.*...
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
react-native-windows@0.30.* successfully installed.
   create windows\.gitignore
   create index.windows.js
   create windows\Arriver\ReactAssets\index.windows.bundle
   create windows\Arriver\Arriver.csproj
   create windows\Arriver.sln
   create windows\Arriver\Arriver_TemporaryKey.pfx
```

**Comment by rozele** [comment]
Those all look like warnings...

**Comment by kcfgl** [comment]
They definitely are.  Just unsure why those 4 files were not created by the plugin.  The list of created files is lower than when using the test project.  

I tried rerunning the plugin, but it created the same files. 

```
Installing react-native-windows@0.30.*...
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
react-native-windows@0.30.* successfully installed.
identical windows\.gitignore
identical index.windows.js
identical windows\Arriver\ReactAssets\index.windows.bundle
 conflict windows\Arriver\Arriver.csproj
? Overwrite windows\Arriver\Arriver.csproj? overwrite
    force windows\Arriver\Arriver.csproj
 conflict windows\Arriver.sln
? Overwrite windows\Arriver.sln? overwrite
    force windows\Arriver.sln
identical windows\Arriver\Arriver_TemporaryKey.pfx
```

**Comment by rozele** [comment]
Ah, just don't worry about the warnings, I don't think they are caused by missing files, I think they're just stuff we need to clean up.  Sorry for the confusion.  Does the project build and run otherwise?

**Comment by rozele** [comment]
Okay, that's really bizarre that those files are not generated.  It looks like they were generated in your previous run (WinRNTest), so I'm not sure where the issue would be coming from.

**Comment by kcfgl** [comment]
I cleared out the files and reran, but no luck.  I'm at a loss :-/

Just to double check I did the following in WinRNTest

- Cleared out windows files
- Checked that the main dependencies of my package.json (WinRNTest) and package.json (Arriver) matched
- Rolled back to the RC version of plugin, reran Arriver.  Didn't generate the other files
- Reran WinRNTest ... generated all the files (including the images, which have never generated in Arriver)
- Removed all the windows files again from WinRNTest and reran against 0.30.0.  Everything generated successfully
- Matched my two project files almost identically (except for the name) and reran WinRNTest.... everything generated successfully.

So now I'm scratching my head.  WinRNTest was generated from cmd on Windows VM. No edits. Arriver was generated on the Mac side, with edits and more JS files.

Let me know if there is anything else you can think for me to try and I'll do it.  Thanks again for sticking this out with me!

**Comment by rozele** [comment]
Okay, running rnpm windows from a Mac very well could be the issue.  This is actually something I haven't tried yet.  My recommendation would be to clone your project on the Windows device and run everything there.  I'll file a backlog issue to investigate the init scripts on Mac.  You'll need to be on Windows to run the build anyway.

**Comment by kcfgl** [comment]
I'll try to clone the project and see if that works.  It certainly seems like trying to build from a shared folder on the VM could be the issue.  I'll let you know how it goes!

**Comment by kcfgl** [comment]
@rozele Sorry for the delay, I thought I added this comment yesterday!  Your recommendation worked successfully and your theory appears to be correct that the plugin will not generate all the files if you're working in a shared directory. 

Steps to generate the files successfully (and build within VS)

- Cloned the project from my Mac to the Parallels VM
- I did NOT clone the node_modules directory
- Installed the node modules from cmd in the cloned directory on VM
- Ran npm install --save-dev rnpm-plugin-windows
- Ran rnpm windows 
- All the required files generated successfully.  
- Build and deploy in VS on VM successfully

Thanks again for all your help getting me set up.  Excited to get an on Windows.

**Comment by kcfgl** [comment]
@rozele I've run into a new issue.  Possibly related, but possibly not so I'll start here with it.

I can build and deploy successfully on VM.  But, changes to index.windows.js are not factored into the build.  Its as if things are perpetually cached.  I started with the boiler plate code.  Deployed to confirm it was working, then switched up index.windows.js to actually run my app.

`'use strict';

import { AppRegistry } from 'react-native'
import setup from './js/setup'
AppRegistry.registerComponent('Arriver', setup);`

This code works on Android and iOS.  But running locally, its just showing the old code.  I've started and the packager.  I've also closed out of VS and opened it back up.

Any thoughts on what might be happening?  Thanks.

**Comment by rozele** [comment]
Is it possible to repro outside the context of your app (e.g., with a simple generated app, make some changes to index.windows.js and not see the difference)?  I have not seen this behavior before.

Did the main component name change?  If so, you may need to update the `MainComponentName` property in MainPage.cs (usually, the MainComponentName is just generated to match your NPM package name).

**Comment by Cacowned** [comment]
I have a issue related to the title, but not related to the rest of the thread. Running rnpm windows fails:

C:\repos\ossw\osswReactNative>rnpm windows
C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\node_modules\commander\index.js:41
  this.required = ~flags.indexOf('<');
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at new Option (C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\node_modules\commander\index.js:41:25)
    at Command.option (C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\node_modules\commander\index.js:361:16)
    at forEach.opt (C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\bin\cli:27:25)
    at Array.forEach (native)
    at addCommand (C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\bin\cli:27:6)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\rnpm\bin\cli:35:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

**Comment by rozele** [comment]
@Cacowned what versions of rnpm-plugin-windows and rnpm?

**Comment by Cacowned** [comment]
Fresh install using the getting started from the readme:
Install rnpm via NPM, globally (i.e., npm install -g rnpm).
Install rnpm-plugin-windows from NPM (i.e., npm install --save-dev rnpm-plugin-windows).

rnpm-plugin-windows@0.2.0-rc.0
rnpm@1.9.0

**Comment by rozele** [comment]
@Cacowned sorry about that, surprised that `npm install --save-dev rnpm-plugin-windows` installed the RC version.  Can you run `npm install --save-dev rnpm-plugin-windows@0.1.*`?

We're in the process of getting all the `react-native-windows` CLI stuff integrated as plugins to the `react-native-cli` (https://github.com/ReactWindows/react-native-windows/pull/552) and there are conflicts in the declarative syntax for rnpm plugins between version 0.1.* and 0.2.* (sorry for not using proper semantic versioning, but we're keeping all versions less than 1.0.0 until react-native moves to 1.0.0).

**Comment by Cacowned** [comment]
@rozele that seems to do the trick, thanks!

**Comment by jurosh** [comment]
@rozele I had same issue with: rnpm-plugin-windows@^0.2.0 and rnpm@1.9.0
And it's not RC - so it's really strange.

As you suggested, after I installed rnpm-plugin-windows@0.1.1 it worked well.

**Comment by mpodwysocki** [comment]
Closing as per resolved
